# Generated by Django 5.2.1 on 2025-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_customuser_managers_remove_customuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="full name"
            ),
        ),
    ]
